Repository f-lab-edu/todo-list, pull requests merged in 2023-01, with the labels that each got.

#2 feature: Setting Code Convention
  .editorconfig
  .github/workflows/build.yml
  build.gradle
  config/checkstyle/checkstyle.xml
Labels: enhancement

#4 feature: Setting Code Convention
  .github/workflows/build.yml
Labels: bug

#3 feature: Setting Code Convention
  .editorconfig
  .github/workflows/build.yml
  build.gradle
  config/checkstyle/checkstyle.xml
Labels: enhancement

#7 setting : Update CheckStyle & EditerConfig
  .editorconfig
  build.gradle
  config/checkstyle/checkstyle.xml
  config/checkstyle/naver-checkstyle-rules.xml
  config/checkstyle/naver-intellij-formatter.xml
  src/main/java/com/flab/todo/TodoListApplication.java
Labels: ⚙ Setting

#11 Setting github actions
  .github/workflows/build.yml
  build.gradle
  src/main/java/com/flab/todo/health/HealthController.java
  src/test/java/com/flab/todo/TodoListApplicationTests.java
  src/test/java/com/flab/todo/health/HealthControllerTest.java
Labels: ⚙ Setting, 🌏 Deploy

#13 Sync Dev & Main
  .github/pull_request_template.md
Labels: 📃 Docs

#14 Dev
  .github/workflows/build.yml
Labels: ⚙ Setting

#15 feat : Update Workflow Permissions
  .github/workflows/build.yml
Labels: ⚙ Setting

#20 Feature/#19 컨벤션 수정 및 확정하기
  .github/workflows/build.yml
  README.md
  src/main/java/com/flab/todo/common/dto/empty.txt
  src/main/java/com/flab/todo/common/exception/ErrorResponse.java
Labels: 📃 Docs

#25 #24 Spring Security 세팅
  .gitignore
  build.gradle
  src/main/java/com/flab/todo/common/config/SecurityConfig.java
Labels: ⚙ Setting

#27 feat : Create Global Controller Advice
  src/main/java/com/flab/todo/common/exception/ErrorResponse.java
  src/main/java/com/flab/todo/common/exception/GlobalExceptionHandler.java
  src/main/java/com/flab/todo/common/exception/custom/ForbiddenRequestException.java
  src/main/java/com/flab/todo/common/exception/custom/UnAuthorizedException.java
Labels: ⚙ Setting
